@startuml entity

entity User {
    * names : string
    * lastNames : string
    * mails : array[string]
    * phones : array[string]
    * rol : string
    * roleDependentInfo : <<Doctor|Assistant>>
    * isActive : bool
}

entity Doctor {
    * user: <<User>>
    * collegiateNumber : string
    * specialty : string
}

entity Assistant {
    * user: <<User>>
    * startDate: date
    * endDate: date
    * DPI: string
}

entity Record {
    * doctor : <<Doctor>>
    * template: <<PatientTemplate>> 
    * createdAt : date
    * patient : Object
    \t* names : string
    \t* lastNames : string
    \t* fields : array[object]
    \t[
        \t\t•name: string
        \t\t•type: category
        \t\t options: array[string]
        \t\t•value: location
        \t\t•required: pages
    \t]
    
}

entity PatientTemplate {
    * doctor : <<Doctor>>
    * lastUpdate: date
    * name: string
    * categories: array[string]
    * fields: array[object]
    [
        \t•name: string
        \t•type: category
        \t options: array[string]
        \t•required: pages
        \t description: string
    ]
}

entity FileTemplate {
    * doctor : <<Doctor>>
    * lastUpdate: date
    * name: string
    * metadata: array[object]
    [
        \t•name: string
        \t•type: category
        \t options: array[string]
        \t•required: pages
        \t description: string
    ]
}

entity File {
    * record : <<Record>>
    * template: <<FileTemplate>> 
    * name : string
    * category : string
    * location : string
    * pages : number
    * created_at : date
    * metadata: array[object]
    [
        \t•name: string
        \t•type: category
        \t options: array[string]
        \t•value: location
        \t•required: pages
    ]
}

User -d- Doctor : < is a
User -d- Assistant : < is a

Record -u- Doctor : < owns many
Record -- File  : < references

Doctor -- FileTemplate : > owns many 
Doctor -- PatientTemplate : > owns many

@enduml